
name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: eastus
        template: ./workload/bicep/deploy-baseline.bicep
        parameters: ./workload/bicep/parameters/deploy-baseline-parameters-example.json avdWorkloadSubsId=${{ secrets.AZURE_SUBSCRIPTION }} deploymentPrefix=ARP7 avdVmLocalUserName=${{ secrets.AVDVMLOCALUSERNAME }} avdVmLocalUserPassword=${{ secrets.AVDVMLOCALUSERPASSWORD }} avdIdentityServiceProvider=EntraID avdEnterpriseAppObjectId=${{ secrets.AVDENTERPRISEAPPOBJECTID }} avdDeployMonitoring=true createAvdVnet=false createAvdFslogixDeployment=true createPrivateDnsZones=false deployAlaWorkspace=true avdSessionHostLocation=eastus avdManagementPlaneLocation=eastus existingVnetAvdSubnetResourceId=/subscriptions/0f07e41f-4fbd-45c4-b9a0-3f83193ba03b/resourceGroups/rgFSAVD1/providers/Microsoft.Network/virtualNetworks/fsAVD-VNET/subnets/snet-arpn-spoke1
        failOnStdErr: false
